services:
  backend:
    build: .
    env_file:
      - .env
    restart: always

    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  nginx:
    build: ./nginx 
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

  db:
    image: postgres:17
    restart: always
    env_file:
      - .env
    volumes: 
      - spellbound_data:/var/lib/postgresql/data

volumes:
  spellbound_data:
